#version: '5.51'
volumes:
  prometheus_data: {}

networks:
  trofimovai-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  prometheus:
    container_name: trofimovai-netology-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - pushgateway:pushgateway
    depends_on:
      - pushgateway
      

  pushgateway:
    container_name: trofimovai-netology-pushgateway
    image: prom/pushgateway
    restart: always
    expose:
     - 9091
    ports:
      - "9091:9091"
    networks:
      - trofimovai-my-netology-hw