#version: '5.51'
volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  trofimovai-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  prometheus:
    container_name: trofimovai-netology-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - trofimovai-my-netology-hw
    depends_on:
      pushgateway:
        condition: service_healthy  
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
      

  pushgateway:
    container_name: trofimovai-netology-pushgateway
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - trofimovai-my-netology-hw
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/metrics"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  grafana:
    container_name: trofimovai-netology-grafana
    image: grafana/grafana
    depends_on:
      prometheus:
        condition: service_healthy
    ports:
      - 80:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./grafana/config.ini
    networks:
      - trofimovai-my-netology-hw
    restart: unless-stopped