---
- name: Set dynamic MOTD with IP and hostname
  hosts: all
  become: yes
  vars:
    greeting: "Good day, dear System Administrator!"

  tasks:
    - name: Set dynamic MOTD
      ansible.builtin.copy:
        content: |
          Hostname: {{ ansible_hostname }}
          IP Address: {{ ansible_default_ipv4.address }}
          {{ greeting }}
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'